### ISSUE TITLE
compatible with HA k3s

### ISSUE THREAD

**Issue by tjengbudi** [carlosedp/cluster-monitoring#65]
hello, i run this with HA k3s but the dashboard always show NONE instead of the graph

can this compatible with 2 or more master cluster?

**Comment by carlosedp** [comment]
I never tested this on K3s HA mode. Improvements are welcome :)

**Comment by magikmw** [comment]
I'm running cluster-monitoring on an etcd-enabled k3s cluster with 3 control plane nodes without issues atm.  

@tjengbudi I had some trouble finding the custom dashboards (they are in a folder called Default in dashboard management, see picture below), but that's just my lack of familiarity with Grafana itself.

![obraz](https://user-images.githubusercontent.com/1144870/99538840-d08e4d80-29ad-11eb-9f60-cdfd4f0ae06c.png)

**Comment by tillik** [comment]
I too am trying this out on k3s and noticed after deployment all dashboards are empty in Grafana. I also get an error saying "Template variables could not be initialized: undefined" and there seems to be only a default datasource for Prometheus on http://prometheus-k8s.monitoring.svc:9090

Any ideas, what could lead to this? 

I was basically following this guide (using nginx and metallb instead of traefik and servicelb): 
https://kauri.io/#deploy-prometheus-and-grafana-to-monitor-a-kube/186a71b189864b9ebc4ef7c8a9f0a6b5/a

**Comment by magikmw** [comment]
@tillik 
That guide ommits running plain `make` between `make vendor` and `make deploy`.

No idea otherwise.

**Comment by carlosedp** [comment]
Good to know it works on K3s with HA.
Closing.
